# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RHYME X DESIGN
author: Randy Tolentino
location: Austin, TX
description: > # this means to ignore newlines until "baseurl:"
  Rhyme X Design is a research-driven, experimental hip hop project that uses Design Thinking as a foundation for the creation of dope shit.

url: "https://rhymexdesign.github.io/" # the base hostname & protocol for your site
twitter: https://twitter.com/rhymexdesign
github:  https://github.com/rhymexdesign
slack:  https://rhymexdesign.slack.com
email: rhymexdesign@gmail.com
facebook: https://facebook.com/maker.tolentino


# Build settings
markdown: kramdown
include: [".htaccess", "_images"]
