# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RHYME X DESIGN
author: Randy Tolentino
email: rhymexdesign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rhyme X Design is a project created by Randy Tolentino.

url: "https://rhymexdesign.github.io/" # the base hostname & protocol for your site
twitter_username: rhymexdesign
github_username:  rhymexdesign

# Build settings
markdown: kramdown
include: [".htaccess", "_images"]
